"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-10 03:53:17.752972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banks_name'), 'banks', ['name'], unique=True)
    op.create_table('inhaber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ist_minderjaehrig', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inhaber_name'), 'inhaber', ['name'], unique=True)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('inhaber_id', sa.Integer(), nullable=False),
    sa.Column('kontoart', sa.String(length=50), nullable=False),
    sa.Column('kuendbar_ab', sa.Date(), nullable=True),
    sa.Column('gekuendigt', sa.Boolean(), nullable=False),
    sa.Column('gekuendigt_im_monat', sa.String(length=10), nullable=True),
    sa.Column('kuendigung_bestaetigt', sa.Boolean(), nullable=False),
    sa.Column('freibetrag', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('praemien_auf_sparkonto', sa.Boolean(), nullable=True),
    sa.Column('kontonummer', sa.String(length=50), nullable=True),
    sa.Column('zugangsdaten_gespeichert', sa.Boolean(), nullable=False),
    sa.Column('kommentar', sa.Text(), nullable=True),
    sa.Column('uebersprungene_felder', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['inhaber_id'], ['inhaber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_bank_id'), 'deals', ['bank_id'], unique=False)
    op.create_index(op.f('ix_deals_inhaber_id'), 'deals', ['inhaber_id'], unique=False)
    op.create_table('aufgaben',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('beschreibung', sa.String(length=255), nullable=False),
    sa.Column('erledigt', sa.Boolean(), nullable=False),
    sa.Column('faellig_bis', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aufgaben_deal_id'), 'aufgaben', ['deal_id'], unique=False)
    op.create_table('bedingungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('beschreibung', sa.String(length=255), nullable=False),
    sa.Column('erfuellt', sa.Boolean(), nullable=False),
    sa.Column('faellig_bis', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bedingungen_deal_id'), 'bedingungen', ['deal_id'], unique=False)
    op.create_table('deal_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('bezeichnung', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_urls_deal_id'), 'deal_urls', ['deal_id'], unique=False)
    op.create_table('praemien',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('quelle', sa.String(length=20), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('erhalten', sa.Boolean(), nullable=False),
    sa.Column('auszahlung_erwartet', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_praemien_deal_id'), 'praemien', ['deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_praemien_deal_id'), table_name='praemien')
    op.drop_table('praemien')
    op.drop_index(op.f('ix_deal_urls_deal_id'), table_name='deal_urls')
    op.drop_table('deal_urls')
    op.drop_index(op.f('ix_bedingungen_deal_id'), table_name='bedingungen')
    op.drop_table('bedingungen')
    op.drop_index(op.f('ix_aufgaben_deal_id'), table_name='aufgaben')
    op.drop_table('aufgaben')
    op.drop_index(op.f('ix_deals_inhaber_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_bank_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_inhaber_name'), table_name='inhaber')
    op.drop_table('inhaber')
    op.drop_index(op.f('ix_banks_name'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
