"""kuendigung hinweis

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-10 09:59:00.569754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('kuendigung_hinweis', sa.Text(), nullable=True))
    op.add_column('deals', sa.Column('kuendigung_hinweis_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'kuendigung_hinweis_url')
    op.drop_column('deals', 'kuendigung_hinweis')
    # ### end Alembic commands ###
